[package]
name = "rc2"
version = "0.2.0"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "RC2 block cipher"
documentation = "https://docs.rs/rc2"
repository = "https://github.com/RustCrypto/block-ciphers"
keywords = ["crypto", "rc2", "block-cipher"]
categories = ["cryptography", "no-std"]

[dependencies]
generic-array = "0.8"
block-cipher-trait = "0.5"

[dev-dependencies]
crypto-tests = "0.6"

[badges]
travis-ci = { repository = "RustCrypto/block-ciphers" }
