language: rust
services: docker
sudo: required

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: 1.22.0
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: stable
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

    - env: NAME="aesni test"
      rust: 1.27.0
      script: cd aesni; RUSTDOCFLAGS="-C target-feature=+aes" RUSTFLAGS="-C target-feature=+aes" cargo test
    - env: NAME="aesni test"
      rust: stable
      script: cd aesni; RUSTDOCFLAGS="-C target-feature=+aes" RUSTFLAGS="-C target-feature=+aes" cargo test
    - env: NAME="aesni test"
      rust: nightly
      script: cd aesni; RUSTDOCFLAGS="-C target-feature=+aes" RUSTFLAGS="-C target-feature=+aes" cargo test

    - env: TARGET=i686-unknown-linux-gnu
      rust: stable
    - env: TARGET=powerpc-unknown-linux-gnu
      rust: stable
    - env: TARGET=powerpc64-unknown-linux-gnu
      rust: stable
    - env: TARGET=thumbv7em-none-eabi
      rust: nightly
      script: ./build_nostd.sh
      install:
        - cargo install xargo --force
        - rustup target install armv7-unknown-linux-gnueabihf
        - rustup component add rust-src

install:
  - curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git japaric/cross --force
  - source ~/.cargo/env || true

script:
  - cross test --verbose --all --release --target $TARGET

cache: cargo
