[workspace]
members = [
    "aes",
    "blowfish",
    "cast5",
    "des",
    "idea",
    "kuznyechik",
    "magma",
    "rc2",
    "serpent",
    "sm4",
    "speck",
    "twofish",
    "threefish",
]

[profile.dev]
opt-level = 2
