[workspace]
members = [
    "blowfish",
    "block-modes",
    "des",
    "kuznyechik",
    "magma",
    "rc2",
    "twofish"
]

[patch.crates-io]
block-cipher-trait = { git = "https://github.com/RustCrypto/traits" }
crypto-tests = { git = "https://github.com/RustCrypto/utils" }
crypto-mac = { git = "https://github.com/RustCrypto/traits" }
digest = { git = "https://github.com/RustCrypto/traits" }
