[package]
name = "cast5"
version = "0.6.0"
description = "CAST5 block cipher"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/cast5"
repository = "https://github.com/RustCrypto/block-ciphers"
keywords = ["crypto", "cast5", "block-cipher"]
categories = ["cryptography", "no-std"]

[dependencies]
block-cipher-trait = "0.6"
opaque-debug = "0.2"
byteorder = { version = "1", default-features = false }

[dev-dependencies]
block-cipher-trait = { version = "0.6", features = ["dev"] }

[features]
default = []

[badges]
travis-ci = { repository = "RustCrypto/block-ciphers" }
