[package]
name = "cast5"
version = "0.7.0-pre"
description = "CAST5 block cipher"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
documentation = "https://docs.rs/cast5"
repository = "https://github.com/RustCrypto/block-ciphers"
keywords = ["crypto", "cast5", "block-cipher"]
categories = ["cryptography", "no-std"]

[dependencies]
block-cipher = "= 0.7.0-pre"
opaque-debug = "0.2"
byteorder = { version = "1", default-features = false }

[dev-dependencies]
block-cipher = { version = "= 0.7.0-pre", features = ["dev"] }

[features]
default = []
