[package]
name = "idea"
version = "0.0.1"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 AND MIT"
description = "IDEA block cipher"
documentation = "https://docs.rs/idea"
repository = "https://github.com/RustCrypto/block-ciphers"
keywords = ["crypto", "idea", "block-cipher"]
categories = ["cryptography", "no-std"]

[dependencies]
block-cipher-trait = "0.6"
opaque-debug = "0.2"

[badges]
maintenance = { status = "experimental" }
travis-ci = { repository = "RustCrypto/block-ciphers" }
