[package]
name = "idea"
version = "0.0.1"
description = "IDEA block cipher"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 AND MIT"
readme = "README.md"
edition = "2018"
documentation = "https://docs.rs/idea"
repository = "https://github.com/RustCrypto/block-ciphers"
keywords = ["crypto", "idea", "block-cipher"]
categories = ["cryptography", "no-std"]

[dependencies]
block-cipher = "= 0.7.0-pre"
opaque-debug = "0.2"

[dev-dependencies]
block-cipher = { version = "= 0.7.0-pre", features = ["dev"] }

[badges]
maintenance = { status = "experimental" }
