[package]
name = "aesni"
version = "0.7.0-pre"
description = "AES (Rijndael) block ciphers implementation using AES-NI"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
edition = "2018"
documentation = "https://docs.rs/aesni"
repository = "https://github.com/RustCrypto/block-ciphers"
keywords = ["crypto", "aes", "rijndael", "block-cipher"]
categories = ["cryptography", "no-std"]

[dependencies]
block-cipher = "= 0.7.0-pre"
opaque-debug = "0.2"
stream-cipher = { version = "= 0.4.0-pre", optional = true }

[dev-dependencies]
block-cipher = { version = "0.7.0-pre", features = ["dev"] }
stream-cipher = { version = "= 0.4.0-pre", features = ["dev"] }

[features]
default = ["ctr"]
ctr = ["stream-cipher"]
nocheck = []

[package.metadata.docs.rs]
rustc-args = ["-C", "target-feature=+aes,+ssse3"]
rustdoc-args = ["-C", "target-feature=+aes,+ssse3"]
